// Edge-rendered 1200×630 social cards. Match the explorer's dark theme, using
// a compact masthead, page/entity identity and a quiet metadata rail.
// workers-og remains lazy so its WASM never enters the client/SSR route graph.
import { OG_CARD_VERSION, OG_LIMITS } from "./metagraphed/og-card-limits.ts";
import { clampText } from "./metagraphed/truncate.ts";

type WorkersOg = typeof import("workers-og");

const OG_PATH = "/og";
const SUBTITLE = "The Bittensor subnet integration registry";
const WORDMARK = "Metagraphed";

// Satori cannot resolve CSS variables. These renderer tokens mirror the
// canonical .dark values in ui-kit/styles.css; a parity test guards drift.
export const OG_THEME = {
  canvas: "#161616",
  layer: "#1f1f1f",
  raised: "#2a2a2a",
  ink: "#f2f2f2",
  muted: "#a3a3a3",
  rule: "rgba(255, 255, 255, 0.11)",
  brand: "#30ffc0",
  accent: "#3ddc97",
  good: "#3fc66e",
  warn: "#e9b84a",
  bad: "#ff6b6f",
  unknown: "#7d7d7d",
} as const;
const HEALTH_COLORS: Record<string, string> = {
  ok: OG_THEME.good,
  warn: OG_THEME.warn,
  down: OG_THEME.bad,
  unknown: OG_THEME.unknown,
};

/**
 * Whether a crawler-supplied `status` is one of the four states.
 *
 * `Object.hasOwn`, deliberately, not `key in HEALTH_COLORS`: `in` walks the
 * prototype chain, so `?status=constructor` (or `toString`, or `valueOf`)
 * would pass the check and then interpolate a stringified function into the
 * card's inline CSS. Own-property only.
 */
function isHealthState(value: string): boolean {
  return Object.hasOwn(HEALTH_COLORS, value);
}

const DEFAULT_TITLE = "Metagraphed";
const CACHE_CONTROL = "public, max-age=86400, stale-while-revalidate=604800";

/**
 * The brand "M" mark (the same brand-kit geometry src/og-image.ts uses),
 * emitted as an <img> data URI rather than inline <svg> for reliable satori
 * rasterization.
 *
 * One path supplies both the mint masthead mark and fixture logo fills.
 * Coordinates are rounded to 2dp; at a 0–750 user space scaled to 512px the
 * rounding remains well under a tenth of a pixel.
 */
const MARK_PATH =
  "M 315.5,1.2 C 313.4,1.7 281.7,32.8 206.5,107.9 C 146.5,167.9 99.3,214.4 97.7,215 C 95.9,215.6 79.4,216 52.3,216 C 11.4,216 9.6,216.1 6.5,218 C -0.4,222.3 0,215.8 0,328.7 C 0,428.5 0,430.6 2,433.8 C 6,440.3 12.9,442.5 19.5,439.4 C 21.3,438.6 70.9,389.4 130.6,329.3 C 223.9,235.5 239.2,220.4 243.8,218.4 C 249,216 249.5,216 281.8,216 C 312.4,216 314.7,216.1 317.7,218 C 319.4,219 321.5,220.9 322.2,222.2 C 323.2,224 323.6,245.1 324,328 L 324.5,431.5 L 326.8,434.8 C 331,440.6 338.1,442.6 343.8,439.6 C 345.3,438.8 395.8,388.8 456,328.5 C 516.2,268.2 566.7,218.2 568.2,217.4 C 570.4,216.3 577.3,216 605.2,216 C 637.4,216 639.7,216.1 642.7,218 C 644.4,219 646.5,220.9 647.2,222.2 C 648.2,224 648.6,245.7 649,331.7 C 649.5,438.1 649.5,438.9 651.6,441.7 C 654.8,446.1 659.7,448.2 665,447.5 C 669.4,447 670.6,445.9 707.3,409.2 C 728.1,388.5 745.8,370.3 746.6,368.8 C 747.8,366.5 748,354.9 748,295.8 C 748,228 747.9,225.4 746,222.3 C 742.5,216.5 742.6,216.5 703.3,216 C 668.7,215.5 667,215.4 664.3,213.4 C 662.8,212.3 660.7,209.8 659.8,207.9 C 658.1,204.7 658,197.9 658,107.8 C 658,-0.7 658.4,5.8 650.8,1.9 C 646.6,-0.2 643.4,-0.5 639.3,1.1 C 637.7,1.7 590.2,48.6 529.9,109.1 L 423.3,216.1 L 382.7,215.8 C 343.5,215.5 342.1,215.4 339.3,213.4 C 337.8,212.3 335.7,209.8 334.8,207.9 C 333.1,204.7 333,197.9 333,107.7 C 333,4.1 333.2,8.2 328.1,3.6 C 325.6,1.3 319.5,0.1 315.5,1.2";

/** `data:` URI for the mark at an arbitrary fill. */
export function markDataUri(fill: string): string {
  const svg =
    `<svg xmlns="http://www.w3.org/2000/svg" width="512" height="512" viewBox="0 0 512 512" fill="none">` +
    `<path transform="translate(81.920,151.738) scale(0.46545)" d="${MARK_PATH}" fill="${fill}"/></svg>`;
  return `data:image/svg+xml;base64,${btoa(svg)}`;
}

const LOGO_DATA_URI = markDataUri(OG_THEME.brand);

/** Generated by scripts/render-og-preview.ts from the same card renderer. */
export const OG_FALLBACK_PATH = "/og-fallback.png";

type EdgeCache = {
  match(request: Request): Promise<Response | undefined>;
  put(request: Request, response: Response): Promise<void>;
};

const cacheStorage = (globalThis as { caches?: { default?: EdgeCache } }).caches?.default ?? null;

/**
 * Make a value safe to interpolate into the HTML string satori parses.
 *
 * This DELETES the two structural characters rather than escaping them, and
 * that is deliberate: workers-og's parser does NOT decode HTML entities in
 * text nodes. Verified against the deployed Worker, not assumed --
 * `/og?title=Agents %26 MCP` rendered the literal characters `& a m p ;`,
 * eight tofu boxes wide, because the subset had no glyph for most of them.
 * So the previous `&` -> `&amp;` escaping was not protecting the card; it was
 * the thing corrupting it, on every title with an ampersand in it.
 *
 * Only `<` and `>` can change how the markup parses, so only they have to go.
 * Removing them is strictly safer than escaping: the character cannot appear
 * in the output at all, so no tag can be formed no matter how the parser
 * behaves. Everything else -- `&`, quotes, apostrophes -- is ordinary text and
 * is passed through untouched, which is what makes it render correctly.
 *
 * This is safe only because no caller-supplied value reaches an ATTRIBUTE:
 * the one attribute carrying dynamic data is the icon's `src`, and that is a
 * data URI this module builds itself (see resolveIcon). Keep it that way.
 */
export function sanitizeText(value: string): string {
  return value.replace(/[<>]/g, "");
}

export function normalizeTitle(value: string | null): string {
  return clampText((value || "").trim() || DEFAULT_TITLE, OG_LIMITS.title);
}

/**
 * The card's second line. Entity pages pass their own (#8257) -- "SN64 ·
 * 0.083τ · healthy" says far more in a link unfurl than the same generic
 * tagline on every page did. Falls back to the tagline when absent, and is
 * bounded like the title so a long one can't overflow the card.
 */
export function normalizeSubtitle(value: string | null): string {
  return clampText((value || "").trim() || SUBTITLE, OG_LIMITS.subtitle);
}

/**
 * Generic bounded-text normalizer for the #8489 entity params.
 *
 * Returns null (not "") for an absent/blank value so every call site can use a
 * plain truthiness check, and the card's own fallback path is a single
 * `?:` rather than scattered emptiness checks.
 */
export function normalizeParam(value: string | null, max: number): string | null {
  return clampText(value, max) || null;
}

/** One "LABEL / value" cell in the card's stat rail. */
export interface OgStat {
  label: string;
  value: string;
}

/**
 * Read the entity params off the query string.
 *
 * Every value is bounded here and escaped at render, so a crawler-supplied
 * query can neither overflow the card nor inject markup into the string satori
 * parses -- the same treatment title/subtitle already had, extended to the new
 * fields rather than trusting them because they're "ours".
 *
 * Stats are read as up to THREE `stat`/`statv` pairs. Three is the cap because
 * the rail is a single row and a fourth cell either wraps or shrinks the type
 * below legibility at unfurl size -- measured on a real render, at the 1200px
 * card width, against the "metagraph.sh" lockup that shares the band. Three
 * also matches what the product itself considers headline-worthy: the subnet
 * masthead's KPI band (#8247) leads with price, emission share and total
 * stake, and those are exactly the three a shared subnet link should carry.
 *
 * `entity` and `status` are the two non-text params:
 *   - `entity=1` marks a card for a NAMED THING (a subnet, a validator, an
 *     account) as opposed to one of our own routes. It decides the avatar
 *     slot's fallback -- see renderCardMarkup -- and is a flag rather than an
 *     inference because "has an eyebrow" stopped being a usable proxy once
 *     every route got one.
 *   - `status` is a health state from the same four-value vocabulary as the
 *     site's health pill, rendered as a coloured dot. Anything else is
 *     dropped rather than guessed at.
 */
export function readCardParams(params: URLSearchParams): {
  eyebrow: string | null;
  stats: OgStat[];
  logoHost: string | null;
  logoPath: string | null;
  entity: boolean;
  status: string | null;
} {
  const eyebrow = normalizeParam(params.get("eyebrow"), OG_LIMITS.eyebrow);
  const logoHost = normalizeLogoHost(params.get("logo"));
  const logoPath = normalizeLogoPath(params.get("logop"));
  const entity = params.get("entity") === "1";
  const rawStatus = (params.get("status") || "").trim().toLowerCase();
  const status = isHealthState(rawStatus) ? rawStatus : null;
  const stats: OgStat[] = [];
  for (const [labelKey, valueKey] of [
    ["stat1", "stat1v"],
    ["stat2", "stat2v"],
    ["stat3", "stat3v"],
  ] as const) {
    const label = normalizeParam(params.get(labelKey), OG_LIMITS.statLabel);
    const value = normalizeParam(params.get(valueKey), OG_LIMITS.statValue);
    // Both halves required: a value with no label is unreadable, and a label
    // with no value is an empty promise.
    if (label && value) stats.push({ label, value });
  }
  return { eyebrow, stats, logoHost, logoPath, entity, status };
}

/**
 * The icon-proxy URL for a host.
 *
 * Kept next to normalizeLogoHost (which is what makes the host safe to put
 * here) and separate from the markup, because the markup must not know about
 * the network: handleOgImage resolves this to an inline data URI BEFORE
 * rendering so a 404 can fall back to a monogram. satori has no `onerror`, so
 * an unresolvable <img> paints an empty tile forever -- which is exactly what
 * a validator like tao.bot got, since no favicon aggregator has it.
 */
export function iconProxyUrl(host: string): string {
  return `https://api.metagraph.sh/api/v1/icon?host=${encodeURIComponent(host)}&size=128&theme=light`;
}

/**
 * Validate the `logo` param as a bare public DNS name.
 *
 * This is the security-critical one. /og is unauthenticated and crawler-
 * reachable, so accepting a URL here would let anyone make this Worker issue
 * an outbound request to a host of their choosing. Instead the param is a
 * HOSTNAME, and the card renders it through the existing SSRF-safe icon proxy
 * (src/icon-proxy.ts), which only ever fetches fixed favicon-aggregator
 * origins and passes the host as a query value — never as the request target.
 *
 * Rejects anything that isn't a plain dotted DNS label: schemes, slashes,
 * userinfo, ports, IP literals, and the localhost/.local/.internal family,
 * mirroring the proxy's own validation rather than trusting it blindly.
 */
/**
 * The registry's own logo assets, the only paths `logop` may name.
 *
 * Two shapes, both committed under apps/ui/public/logos and both measured
 * against the live registry: subnets carry a content-addressed cache entry
 * (`cache/<sha256>.<ext>`, all 60 of them), providers a slug (`<slug>.<ext>`,
 * 102 of 138). Pinning the whole path rather than sanitizing it is what makes
 * this safe: the name charset excludes `.`, so `..` cannot be spelled, and
 * there is no way to name anything but an image this repo ships.
 */
const LOGO_ASSET_PATH =
  /^\/logos\/(?:cache\/[0-9a-f]{64}|[a-z0-9][a-z0-9-]{0,62})\.(?:png|svg|jpg|jpeg|webp)$/;

/**
 * Validate the `logop` param as one of OUR OWN cached logo assets.
 *
 * Why this exists alongside `logo` (a hostname resolved through the icon
 * proxy): the registry stores a subnet's logo as a first-party cached copy,
 * `https://metagraph.sh/logos/cache/<sha256>.png`. Reducing that to a HOST the
 * way every other candidate is reduced yields `metagraph.sh` and then asks a
 * favicon aggregator for OUR site's icon -- throwing away a working, curated
 * image. All 60 subnets that have a logo hit that path, so all 60 cards showed
 * a two-letter monogram.
 *
 * A path is safe here where a URL would not be because the ORIGIN is not the
 * caller's to choose: the asset is read through the Worker's own ASSETS
 * binding, never fetched. That also sidesteps the trap that makes the obvious
 * implementation fail -- this Worker serves metagraph.sh, and a Worker cannot
 * fetch its own custom domain (Cloudflare answers 522).
 */
export function normalizeLogoPath(value: string | null): string | null {
  const raw = (value || "").trim();
  return LOGO_ASSET_PATH.test(raw) ? raw : null;
}

export function normalizeLogoHost(value: string | null): string | null {
  const raw = (value || "").trim().toLowerCase();
  if (!raw || raw.length > OG_LIMITS.logoHost) return null;
  // Plain DNS name only: labels of alphanumerics/hyphens, at least one dot,
  // and a non-numeric TLD (which also rules out bare IPv4 literals).
  if (!/^(?=.{1,253}$)([a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,}$/.test(raw)) return null;
  if (/(^|\.)(localhost|local|internal|test|invalid|example)$/.test(raw)) return null;
  return raw;
}

/**
 * Title size, stepped down by length.
 *
 * A fixed 68px is right for the short names that dominate in practice
 * ("Chutes", "tao.bot", a truncated ss58), but `normalizeTitle` allows up to
 * 110 characters, and at 68px that wraps to four lines and shoves the stat
 * rail off the bottom of the card -- verified by rendering the pathological
 * case, not assumed. Satori has no reliable line-clamp, so the deterministic
 * fix is to scale the type to the content. Every returned size is chosen so
 * the worst case at that length still fits the 630px canvas.
 */
export function titleFontSize(length: number): number {
  if (length <= 24) return 68;
  if (length <= 48) return 54;
  return length > 90 ? 36 : 42;
}

/**
 * Two-character monogram for an entity with no resolvable logo.
 *
 * Byte-for-byte the same rule as ui-kit's `monogramFor` (BrandIcon): two or
 * more words -> first letter of each; otherwise the first two characters;
 * uppercased. Copied rather than imported because this module is Worker-side
 * and must not pull the React component graph in.
 *
 * The point is that the site's BrandIcon ALWAYS renders something -- an image
 * when it has one, a monogram chip otherwise -- so a validator like "tao.bot"
 * shows "TA" rather than a blank space. The card previously rendered nothing
 * at all without a logo, which is why entity cards looked unfinished next to
 * the same entity on the site.
 */
export function monogramFor(title: string): string {
  const source = title.trim();
  if (!source) return "··";
  const parts = source.split(/\s+/).filter(Boolean);
  if (parts.length >= 2) return (parts[0]![0]! + parts[1]![0]!).toUpperCase();
  return source.slice(0, 2).toUpperCase();
}

/**
 * The card markup.
 *
 * satori is strict: any element with more than one child needs an explicit
 * `display:flex`, and text must live in leaf nodes. Every container below sets
 * it deliberately -- a missing one renders as a blank card, not a warning.
 *
 * Two layout details, both found by rendering the real markup and MEASURING
 * it rather than eyeballing a thumbnail:
 *
 *  1. The root carries EXPLICIT 1200x630 pixel dimensions, not 100%/100%.
 *     Percentage sizing has to resolve against a parent, and when it doesn't
 *     the card lays out at its intrinsic content height instead of the canvas
 *     -- which silently pushed the stat rail past the bottom edge, cropped
 *     (measured 774px against a 630px canvas).
 *  2. The padded inner wrapper is `position:relative`. Absolutely-positioned
 *     elements paint above non-positioned in-flow content, so the decorative
 *     diagonal was washing out the subtitle behind it -- visible only by
 *     looking at a real render. Positioning the content wrapper lifts the copy
 *     back above the decoration, and the text columns are additionally capped
 *     short of the diagonal's footprint so legibility never depends on the
 *     stacking rule alone.
 *  3. Padding lives on an INNER wrapper, never on the sized root. With the CSS
 *     default `box-sizing: content-box`, width:1200px + 80px horizontal
 *     padding renders 1360px wide -- the card silently outgrows its own
 *     canvas. Separating "the box that is exactly the canvas" from "the box
 *     that has the padding" is unambiguous under either box model, and is the
 *     same structure src/og-image.ts (the landing card) already uses.
 *
 * Exported so a test can assert the structure without running the wasm
 * rasterizer.
 */
export function renderCardMarkup(opts: {
  title: string;
  subtitle: string;
  eyebrow: string | null;
  stats: OgStat[];
  /**
   * Already-resolved image src for the avatar slot (a `data:` URI). Resolution
   * happens in handleOgImage, never here -- see iconProxyUrl.
   */
  icon?: string | null;
  /** Card is about a NAMED THING, so an unresolved icon falls back to a monogram. */
  entity?: boolean;
  /** Health state key into HEALTH_COLORS; colours the footer dot. */
  status?: string | null;
}): string {
  const title = sanitizeText(opts.title);
  const subtitle = sanitizeText(opts.subtitle);
  const eyebrow = opts.eyebrow ? sanitizeText(opts.eyebrow).toUpperCase() : "EXPLORER";
  const stats = opts.stats.slice(0, 3);
  const statWidth = stats.length > 2 ? 244 : 300;
  const statCells = stats
    .map((stat) => {
      const valueSize = stat.value.length > 18 ? 22 : stat.value.length > 11 ? 28 : 36;
      return `<div style="display:flex;flex-direction:column;width:${statWidth}px;padding-right:24px;">
      <div style="display:flex;font-size:16px;font-weight:500;line-height:1.2;color:${OG_THEME.muted};letter-spacing:1px;word-break:break-word;">${sanitizeText(stat.label.toUpperCase())}</div>
      <div style="display:flex;font-family:'Geist Mono','Inter';font-size:${valueSize}px;font-weight:500;color:${OG_THEME.accent};line-height:1.2;margin-top:10px;word-break:break-all;">${sanitizeText(stat.value)}</div>
    </div>`;
    })
    .join("");
  // Third-party logos retain a light tile for dark-on-transparent artwork.
  // Missing entity logos use the same quiet monogram treatment as the site.
  const tile =
    opts.entity || opts.icon
      ? `<div style="display:flex;align-items:center;justify-content:center;width:88px;height:88px;flex-shrink:0;margin-right:28px;background:${opts.icon ? "#ffffff" : OG_THEME.raised};border:1px solid ${OG_THEME.rule};border-radius:4px;">
       ${
         opts.icon
           ? `<img src="${opts.icon}" style="width:64px;height:64px;object-fit:contain;" />`
           : `<div style="display:flex;font-size:32px;font-weight:700;color:${OG_THEME.accent};">${sanitizeText(monogramFor(opts.title))}</div>`
       }
       </div>`
      : "";
  const dotColor =
    (opts.status && isHealthState(opts.status) && HEALTH_COLORS[opts.status]) || OG_THEME.brand;
  // workers-og keeps inter-tag whitespace as flex children. Remove those
  // empty nodes so native previews and edge layout agree.
  return `<div style="position:relative;display:flex;flex-direction:column;width:1200px;height:630px;background:${OG_THEME.canvas};color:${OG_THEME.ink};font-family:'Geist','Inter';overflow:hidden;">
    <div style="display:flex;height:4px;width:1200px;background:${OG_THEME.rule};flex-shrink:0;">
      <div style="display:flex;width:192px;height:4px;background:${OG_THEME.brand};"></div>
    </div>
    <div style="display:flex;align-items:center;justify-content:space-between;height:104px;padding:0 64px;border-bottom:1px solid ${OG_THEME.rule};flex-shrink:0;">
      <div style="display:flex;align-items:center;">
        <img src="${LOGO_DATA_URI}" style="width:50px;height:50px;" />
        <div style="display:flex;font-size:30px;font-weight:700;letter-spacing:-0.5px;margin-left:8px;">${WORDMARK}</div>
      </div>
      <div style="display:flex;max-width:440px;word-break:break-word;padding:8px 12px;border:1px solid ${OG_THEME.rule};font-size:18px;font-weight:500;color:${OG_THEME.accent};letter-spacing:1px;">${eyebrow}</div>
    </div>
    <div style="display:flex;flex:1;align-items:center;padding:32px 64px;">
      ${tile}
      <div style="display:flex;flex-direction:column;width:${tile ? 956 : 1072}px;">
        <div style="display:flex;font-size:${titleFontSize(opts.title.length)}px;font-weight:700;line-height:1.08;letter-spacing:-1px;word-break:break-word;">${title}</div>
        <div style="display:flex;font-size:28px;font-weight:400;line-height:1.35;color:${OG_THEME.muted};margin-top:22px;max-width:940px;word-break:break-word;">${subtitle}</div>
      </div>
    </div>
    <div style="display:flex;align-items:center;justify-content:space-between;height:152px;padding:24px 64px;background:${OG_THEME.layer};border-top:1px solid ${OG_THEME.rule};flex-shrink:0;">
      <div style="display:flex;">${statCells}</div>
      <div style="display:flex;align-items:center;flex-shrink:0;">
        <div style="display:flex;width:8px;height:8px;background:${dotColor};margin-right:12px;"></div>
        <div style="display:flex;font-size:22px;font-weight:500;color:${OG_THEME.muted};">metagraph.sh</div>
      </div>
    </div>
  </div>`.replace(/>\s+</g, "><");
}

/**
 * The exact set of characters the card will paint, derived FROM the rendered
 * markup rather than re-listed by hand.
 *
 * Fonts are subset to `text=` for size, so any character that isn't in this
 * string rasterizes as a tofu box. Maintaining a parallel list of "everything
 * we render" is a bug generator: it silently drifts every time the markup
 * transforms a value. It already bit twice — stat labels are rendered
 * `.toUpperCase()`, and so is the eyebrow pill, but only the former was
 * mirrored into the hand-written list, so an eyebrow like "Validator" painted
 * "V" followed by eight tofu boxes wherever the title happened not to supply
 * the capitals.
 *
 * Deriving from the markup makes that impossible: whatever the template
 * renders is by construction what gets subset.
 *
 * Stripping tags is the whole job -- their attributes go with them, since they
 * live inside `<...>`, which is what keeps the inlined icon's base64 and every
 * style declaration out of the font request. There is deliberately no entity
 * decoding step: `sanitizeText` no longer emits entities (workers-og does not
 * decode them, so emitting them was the bug), and a decode here would have
 * quietly hidden that by subsetting the glyph the card was never going to
 * paint.
 */
export function glyphsForMarkup(markup: string): string {
  const text = markup.replace(/<[^>]*>/g, "");
  // Deduped: subsetting is per code point, so repeats never bought anything.
  // Spread, not split(""): a split would cut astral characters in half and
  // subset two broken halves of an emoji.
  return [...new Set([...text])].join("");
}

/** U+0020..U+007E, built rather than typed so no escaping can go wrong. */
const ASCII_PRINTABLE = Array.from({ length: 0x7e - 0x20 + 1 }, (_, index) =>
  String.fromCharCode(0x20 + index),
).join("");

/**
 * The non-ASCII characters this card is *designed* to paint.
 *
 * `…` is emitted by all three normalizers when they truncate; `·` and `—`
 * separate the clauses of an entity subtitle; `τ` is in every TAO value. The
 * rest are the typographic characters ordinary prose drags in (smart quotes
 * from a subnet description, a `×`, a `°`). All are one glyph each.
 */
const TYPOGRAPHIC_GLYPHS = "·×–—‘’“”•…→τ€°";

/**
 * The repertoire EVERY card is subset to, whatever it happens to say.
 *
 * Requesting a fixed set rather than exactly this card's characters is what
 * makes the font request cacheable: the URL is then identical for almost every
 * card, so `caches.default` (and the per-isolate memo below) actually hit,
 * instead of missing on every render because the query carried that card's
 * prose. Each fixed subset is paid once per isolate, while unusual glyphs
 * extend the requested repertoire without changing ordinary card requests.
 *
 * It also makes coverage DETERMINISTIC. A per-card subset means the answer to
 * "is this glyph in the font" depends on what the card says, which is exactly
 * the coupling that produced tofu; with a fixed base, anything in this string
 * is always present and only genuinely exotic input takes the slow path.
 */
export const CARD_GLYPHS = ASCII_PRINTABLE + TYPOGRAPHIC_GLYPHS;

/**
 * The `text=` subset request for a card: the fixed repertoire, plus whatever
 * this card paints that isn't already in it.
 *
 * Extras are sorted so two cards needing the same exotic characters produce the
 * same URL and share a cache entry, and control characters are dropped — the
 * markup is full of newlines between tags, and they are not glyphs.
 */
export function fontSubsetText(markup: string): string {
  const base = new Set(CARD_GLYPHS);
  const extra = [...glyphsForMarkup(markup)]
    .filter((char) => {
      if (base.has(char)) return false;
      const code = char.codePointAt(0) ?? 0;
      return code >= 0x20 && code !== 0x7f && !(code >= 0x80 && code <= 0x9f);
    })
    .sort()
    .join("");
  return CARD_GLYPHS + extra;
}

/**
 * The Google Fonts CSS URL for one subset face.
 *
 * `text` is percent-encoded, and THAT is the whole point of this function
 * existing (#11204). workers-og's own `loadGoogleFont` encodes `family` and
 * interpolates `text` raw:
 *
 *     `https://fonts.googleapis.com/css2?${keys.map(k =>`${k}=${n[k]}`).join("&")}`
 *
 * So one `%` anywhere in the card's copy — an emission share of `0.61%` is
 * enough — leaves a bare `%` in the query value, Google stops decoding the
 * whole parameter, and the `%E2%80%94` / `%E2%80%A6` / `%CF%84` escapes the URL
 * serializer produced for `—`, `…` and `τ` are subset as the LITERAL hex
 * letters instead. Measured against the live endpoint: the same request with
 * the `%` encoded returns all three glyphs, without it returns none of them.
 * That is why every subnet card painted three `.notdef` boxes while a card with
 * no stats rendered the identical subtitle correctly.
 *
 * Encoding the text before handing it to workers-og would fix today's symptom
 * and arm a worse one: a future version that encodes correctly would then
 * double-encode ours, silently, with no test able to see it. Owning the two
 * fetches is ~20 lines and removes the guess entirely.
 */
export function googleFontUrl(family: string, weight: number, text: string): string {
  return (
    "https://fonts.googleapis.com/css2" +
    `?family=${encodeURIComponent(family)}:wght@${weight}` +
    `&text=${encodeURIComponent(text)}`
  );
}

/**
 * An ancient Safari UA, deliberately.
 *
 * Google Fonts serves woff2 to anything modern, and satori cannot parse woff2 —
 * it needs ttf/otf. This UA is what makes the css2 endpoint answer with a
 * `format('truetype')` face. Inherited from workers-og, and load-bearing:
 * change it and every card silently becomes the 1px fallback PNG.
 */
const FONT_USER_AGENT =
  "Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_8; de-at) " +
  "AppleWebKit/533.21.1 (KHTML, like Gecko) Version/5.0.5 Safari/533.21.1";

/** Subset faces are immutable for a given (family, weight, text) — hold them. */
const FONT_CACHE_CONTROL = "public, max-age=2592000";

/**
 * Per-isolate memo of in-flight and resolved faces.
 *
 * Keyed on the CSS URL, which is a total function of (family, weight, text) —
 * so with the fixed repertoire above this is one entry per face for the life of
 * the isolate, and concurrent renders share a single fetch rather than racing.
 */
const fontMemo = new Map<string, Promise<ArrayBuffer>>();

async function fetchFontBinary(
  family: string,
  weight: number,
  text: string,
  fetchImpl: typeof fetch,
): Promise<ArrayBuffer> {
  const cssResponse = await fetchImpl(googleFontUrl(family, weight, text), {
    headers: { "user-agent": FONT_USER_AGENT },
  });
  if (!cssResponse.ok) {
    throw new Error(`Google Fonts CSS ${cssResponse.status} for ${family} ${weight}`);
  }
  // A gstatic font URL never contains ")", so this is bounded rather than the
  // greedy `(.+)` workers-og used.
  const source = (await cssResponse.text()).match(
    /src:\s*url\(([^)]+)\)\s*format\('(?:opentype|truetype)'\)/,
  )?.[1];
  if (!source) throw new Error(`No TrueType face in Google Fonts CSS for ${family} ${weight}`);
  const fontResponse = await fetchImpl(source);
  if (!fontResponse.ok) {
    throw new Error(`Google Fonts binary ${fontResponse.status} for ${family} ${weight}`);
  }
  return await fontResponse.arrayBuffer();
}

/**
 * One subset face, through the isolate memo and the edge cache.
 *
 * workers-og cached the CSS response but never the font binary, and keyed that
 * cache on a URL carrying the card's prose — so in practice it re-fetched both
 * on every uncached card. Caching the binary subsumes the CSS lookup, so a warm
 * isolate renders a card with zero external requests.
 *
 * Both cache layers are best-effort: a cache that is unavailable or refuses the
 * key must degrade to a plain fetch, never fail the card.
 */
export async function loadCardFont(
  family: string,
  weight: number,
  text: string,
  fetchImpl: typeof fetch = fetch,
): Promise<ArrayBuffer> {
  const cssUrl = googleFontUrl(family, weight, text);
  const memoized = fontMemo.get(cssUrl);
  if (memoized) return await memoized;

  const pending = (async () => {
    const cacheKey = new Request(`${cssUrl}&fmt=ttf`);
    try {
      const hit = await cacheStorage?.match(cacheKey);
      if (hit) return await hit.arrayBuffer();
    } catch {
      // No usable edge cache — fetch it.
    }
    const bytes = await fetchFontBinary(family, weight, text, fetchImpl);
    try {
      await cacheStorage?.put(
        cacheKey,
        new Response(bytes, {
          headers: { "cache-control": FONT_CACHE_CONTROL, "content-type": "font/ttf" },
        }),
      );
    } catch {
      // Caching is an optimisation; the face is already in hand.
    }
    return bytes;
  })();

  fontMemo.set(cssUrl, pending);
  // Never memoize a rejection: one Google Fonts hiccup would otherwise blank
  // every card this isolate goes on to render.
  pending.catch(() => fontMemo.delete(cssUrl));
  return await pending;
}

// Match the site's Geist text and Geist Mono figures. Inter remains a
// glyph fallback at each text weight for chain symbols and multilingual titles.
export const CARD_FONT_FACES = [
  { name: "Geist", weight: 700 },
  { name: "Geist", weight: 500 },
  { name: "Geist", weight: 400 },
  { name: "Geist Mono", weight: 500 },
  { name: "Inter", weight: 700 },
  { name: "Inter", weight: 500 },
  { name: "Inter", weight: 400 },
] as const;

function makeCacheKey(url: URL, title: string, subtitle: string): Request {
  const cacheUrl = new URL(url);
  const original = cacheUrl.searchParams;
  const next = new URLSearchParams();
  next.set("title", title);
  next.set("subtitle", subtitle);
  // #8489: the entity params are part of the rendered output, so they MUST be
  // part of the cache key -- otherwise two subnets sharing a title would serve
  // each other's stats from the edge.
  for (const key of [
    "eyebrow",
    "stat1",
    "stat1v",
    "stat2",
    "stat2v",
    "stat3",
    "stat3v",
    "logo",
    "logop",
    "entity",
    "status",
  ]) {
    const value = original.get(key);
    if (value) next.set(key, value);
  }
  // Part of the key, not just the markup: bumping it retires every cached
  // card at once rather than waiting each entry out.
  next.set("v", OG_CARD_VERSION);
  cacheUrl.search = next.toString();
  return new Request(cacheUrl.toString(), { method: "GET" });
}

function withOgHeaders(response: Response): Response {
  const headers = new Headers(response.headers);
  headers.set("cache-control", CACHE_CONTROL);
  headers.set("content-type", "image/png");
  return new Response(response.body, { status: response.status, headers });
}

/**
 * How large an entity icon may be before we decline to inline it.
 *
 * The proxy serves 128px PNGs (~20KB is typical), so this is generous headroom
 * rather than a tuned limit -- its job is to stop a pathological response from
 * being base64'd into the markup, not to reject real icons.
 */
const MAX_ICON_BYTES = 256 * 1024;

/**
 * Fetch an entity icon through our proxy and inline it as a `data:` URI, or
 * return null so the card falls back to a monogram.
 *
 * This exists because satori has no `onerror`. The site can put a broken
 * <img> on the page and let BrandIcon's chain advance to a monogram; a card
 * cannot -- an unresolvable src rasterizes as an empty tile and stays that way
 * in every unfurl for the life of the cache entry. That is exactly what
 * happened to tao.bot: it publishes a favicon, but no aggregator the proxy
 * queries has one, so the proxy 404s and the tile came out blank while the
 * site showed "TA".
 *
 * Resolving here rather than letting satori fetch also means ONE request
 * instead of two, on a response that is edge-cached for a day.
 *
 * Every failure mode returns null rather than throwing: an OG card must render
 * something even when the icon service is down.
 */
async function inlineImage(response: Response): Promise<string | null> {
  if (!response.ok) return null;
  const type = response.headers.get("content-type") || "";
  if (!type.startsWith("image/")) return null;
  const bytes = new Uint8Array(await response.arrayBuffer());
  if (bytes.byteLength === 0 || bytes.byteLength > MAX_ICON_BYTES) return null;
  // The bundled edge rasterizer cannot reliably paint bitmap-backed SVGs.
  // Decline them before selecting a logo tile so the proxy/monogram chain
  // remains available instead of caching a successful blank avatar.
  if (type.startsWith("image/svg+xml") && /<image[\s>]/i.test(new TextDecoder().decode(bytes))) {
    return null;
  }
  // btoa needs a binary string; chunked so a large icon can't blow the
  // argument limit with String.fromCharCode(...spread).
  let binary = "";
  for (let i = 0; i < bytes.length; i += 8192) {
    binary += String.fromCharCode(...bytes.subarray(i, i + 8192));
  }
  return `data:${type.split(";")[0]};base64,${btoa(binary)}`;
}

export async function resolveIcon(
  host: string,
  fetchImpl: typeof fetch = fetch,
): Promise<string | null> {
  try {
    return await inlineImage(await fetchImpl(iconProxyUrl(host)));
  } catch {
    return null;
  }
}

/** The Worker's static-asset binding — what serves apps/ui/public. */
export interface AssetsBinding {
  fetch(input: Request): Promise<Response>;
}

/**
 * Narrow the Worker `env` to its ASSETS binding, or null when absent.
 *
 * Falls back to `globalThis.__env__`, and that fallback is the one that
 * actually fires: this module runs inside the Nitro app, which reaches our
 * fetch handler through `nitroApp.fetch(request)` — a call that carries no env
 * at all. Nitro's Cloudflare entry assigns the real env to `globalThis.__env__`
 * as the first statement of its own fetch handler, before any dispatch, so it
 * is populated by the time a request reaches us. Verified against a real
 * `wrangler dev` build, where the passed env has no ASSETS and this does.
 *
 * The passed env is still preferred: it is the direct, documented route, and
 * keeps this working if the preset ever hands us the real thing.
 */
export function assetsBindingFrom(env: unknown): AssetsBinding | null {
  for (const candidate of [env, (globalThis as { __env__?: unknown }).__env__]) {
    const assets = (candidate as { ASSETS?: unknown } | null | undefined)?.ASSETS;
    if (typeof (assets as AssetsBinding | undefined)?.fetch === "function") {
      return assets as AssetsBinding;
    }
  }
  return null;
}

/**
 * Inline one of our own cached logo assets, read through the ASSETS binding.
 *
 * The binding, not `fetch`: these assets are served by THIS Worker on
 * metagraph.sh, and a Worker fetching its own custom domain gets a 522 rather
 * than the file. Reading the binding is also strictly faster -- no edge round
 * trip at all -- and is what keeps the origin out of the caller's hands.
 *
 * Returns null on anything unexpected so the card falls through to the
 * monogram, exactly as an unresolvable third-party icon does.
 */
export async function resolveLocalLogo(
  path: string,
  assets: AssetsBinding | null,
  origin: string,
): Promise<string | null> {
  if (!assets) {
    console.error(`OG logo: no ASSETS binding, cannot read ${path}`);
    return null;
  }
  try {
    // A Request, not a bare string: the assets binding is a Fetcher, and
    // handing it a constructed Request is the form its own docs use.
    const response = await assets.fetch(new Request(new URL(path, origin).toString()));
    const inlined = await inlineImage(response);
    // The path already passed LOGO_ASSET_PATH, so we believe this asset exists.
    // If it doesn't, a curated logo has gone missing and the card is silently
    // degrading to a monogram -- say so rather than letting it be invisible.
    if (!inlined) {
      console.error(
        `OG logo unresolved: ${path} (${response.status} ${response.headers.get("content-type")})`,
      );
    }
    return inlined;
  } catch (error) {
    console.error(`OG logo read failed: ${path}`, error);
    return null;
  }
}

export async function fallbackImageResponse(env: unknown, origin: string): Promise<Response> {
  try {
    const asset = await assetsBindingFrom(env)?.fetch(
      new Request(new URL(OG_FALLBACK_PATH, origin)),
    );
    if (
      asset?.ok &&
      asset.headers.get("content-type")?.split(";")[0]?.trim().toLowerCase() === "image/png"
    ) {
      return new Response(asset.body, {
        headers: { "cache-control": "public, max-age=60", "content-type": "image/png" },
      });
    }
  } catch {
    /* The fallback is independent of rendering and font availability. */
  }
  return new Response("Preview image unavailable", {
    status: 503,
    headers: { "cache-control": "no-store" },
  });
}

// Render the /og card, or return null when the path doesn't match.
//
// `env` is threaded in for the ASSETS binding only -- it is what lets a card
// carry the registry's own cached logo (see resolveLocalLogo). Optional, so a
// caller without an env still renders every other card correctly.
export async function handleOgImage(request: Request, env?: unknown): Promise<Response | null> {
  const url = new URL(request.url);
  if (url.pathname !== OG_PATH) return null;
  if (request.method !== "GET" && request.method !== "HEAD") {
    return new Response("Method Not Allowed", { status: 405, headers: { allow: "GET, HEAD" } });
  }
  if (url.search.length > OG_LIMITS.query) {
    return new Response("Query Too Large", { status: 414 });
  }

  const normalizedTitle = normalizeTitle(url.searchParams.get("title"));
  const normalizedSubtitle = normalizeSubtitle(url.searchParams.get("subtitle"));
  const { eyebrow, stats, logoHost, logoPath, entity, status } = readCardParams(url.searchParams);
  const cacheKey = makeCacheKey(url, normalizedTitle, normalizedSubtitle);
  let cached: Response | undefined;
  try {
    cached = await cacheStorage?.match(cacheKey);
  } catch {
    /* A cache miss still renders. */
  }
  if (cached) {
    const response = withOgHeaders(cached);
    return request.method === "HEAD" ? new Response(null, response) : response;
  }

  if (request.method === "HEAD") {
    return new Response(null, {
      headers: {
        "cache-control": CACHE_CONTROL,
        "content-type": "image/png",
      },
    });
  }

  // Lazily pull in workers-og (satori + yoga wasm) only now that we're actually
  // rendering — keeps the wasm out of the SSR module graph so `vite dev` works.
  // Failure here returns the fallback PNG rather than throwing, since this runs
  // outside server.ts's try/catch.
  let ImageResponse: WorkersOg["ImageResponse"];
  try {
    ({ ImageResponse } = await import("workers-og"));
  } catch (error) {
    console.error("Failed to load workers-og", error);
    return fallbackImageResponse(env, url.origin);
  }

  // Resolve the entity icon before rendering so an unresolvable one degrades
  // to a monogram instead of an empty tile -- see resolveIcon.
  //
  // Our own cached asset wins when there is one: it is the logo the registry
  // curated for that entity, read straight from the ASSETS binding, where the
  // proxy path is a favicon lookup that may well miss (it has no icon for
  // apex.macrocosmos.ai, for instance).
  const icon =
    (logoPath ? await resolveLocalLogo(logoPath, assetsBindingFrom(env), url.origin) : null) ??
    (logoHost ? await resolveIcon(logoHost) : null);

  // Build the markup FIRST so the font subset can be derived from it -- see
  // glyphsForMarkup for why a hand-maintained glyph list is a bug generator.
  const markup = renderCardMarkup({
    title: normalizedTitle,
    subtitle: normalizedSubtitle,
    eyebrow,
    stats,
    icon,
    entity,
    status,
  });
  // One subset request per face, covering the fixed repertoire plus anything
  // exotic this particular card paints -- see fontSubsetText and googleFontUrl.
  const subsetText = fontSubsetText(markup);
  const loaded = await Promise.allSettled(
    CARD_FONT_FACES.map((face) => loadCardFont(face.name, face.weight, subsetText)),
  );
  // allSettled, not all: a card missing one weight still reads correctly, where
  // one failed request rejecting the whole batch serves a generic fallback for every
  // unfurl until the cache turns over. Only a total failure is unrenderable --
  // satori needs at least one face.
  const fonts = CARD_FONT_FACES.flatMap((face, index) => {
    const result = loaded[index];
    if (result?.status !== "fulfilled") {
      console.error(`OG font unavailable: ${face.name} ${face.weight}`, result?.reason);
      return [];
    }
    return [{ name: face.name, data: result.value, weight: face.weight, style: "normal" as const }];
  });
  if (fonts.length === 0) {
    console.error("Failed to load any OG image font");
    return fallbackImageResponse(env, url.origin);
  }

  try {
    const image = new ImageResponse(markup, { width: 1200, height: 630, fonts });
    const response = withOgHeaders(image);
    try {
      await cacheStorage?.put(cacheKey, response.clone());
    } catch {
      /* Preserve the valid render. */
    }
    return response;
  } catch (error) {
    console.error("Failed to render OG image", error);
    return fallbackImageResponse(env, url.origin);
  }
}
